---
- hosts: "build_servers"
  gather_facts: False
  become: yes
  roles:
    - { role: base, tags: [base, app, azure] }
    - { role: docker, tags: [ app ] }
    - { role: user, tags: [app, azure] }
    - { role: github, tags: [ app ] }
    - { role: azure, tags: [ azure ] }
    - { role: app, tags: [app, azure] }
